version: '3'

services:
  source_postgres:
    image: postgres:15
    ports:
      - '5433:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  # elt_script:
  #   build:
  #     context: ./elt # Directory containing the Dockerfile and elt_script.py
  #     dockerfile: Dockerfile
  #   command: ['python', 'elt_script.py']
  #   networks:
  #     - elt_network
  #   depends_on:
  #     - source_postgres
  #     - destination_postgres
  
  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
  #   command:
  #     [
  #       "run",
  #       "--profiles-dir",
  #       "/root",
  #       "--project-dir",
  #       "/dbt",
  #     ]
  #   networks:
  #     - elt_network
  #   volumes:
  #     - ./custom_postgres:/dbt
  #     - ~/.dbt:/root
  #   depends_on:
  #     - elt_script
  #   environment:
  #     DBT_PROFILE: default
  #     DBT_TARGET: dev

  init-airflow:
    image: apache/airflow:latest
    depends_on:
      - source_postgres
    networks:
      - elt_network
    environment:
      - AIRFLOW__DATABASE__SQLALCHEMY__CONN=postgres+psycopg2://airflow:airflow@source_postgres/airflow
    command: >
      bash -c "airflow db init &&
      docker-compose exec init-airflow airflow users create --username airflow --password password --firstname Yassire --lastname Ammouri --role Admin --email admin@example.com"
      docker-compose exec init-airflow python /opt/airflow/elt/elt_script.py
  

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - source_postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQLALCHEMY__CONN=postgres+psycopg2://airflow:airflow@source_postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=bx98tUlPaRmr9S94dpUFvcSkvqIeSQW54GU7xmwthR0=
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=password

    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && airflow webserver"


  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - source_postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQLALCHEMY__CONN=postgres+psycopg2://airflow:airflow@source_postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=bx98tUlPaRmr9S94dpUFvcSkvqIeSQW54GU7xmwthR0=
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    command: >
      bash -c "airflow db init && airflow scheduler"


networks:
  elt_network:
    driver: bridge
